return {
	{
		"folke/which-key.nvim",
		event = "VeryLazy",
		opts = {
			preset = "helix",
			mappings = vim.g.have_nerd_font,
			keys = vim.g.have_nerd_font and {} or {
				Up = "<Up> ",
				Down = "<Down> ",
				Left = "<Left> ",
				Right = "<Right> ",
				C = "<C-…> ",
				M = "<M-…> ",
				D = "<D-…> ",
				S = "<S-…> ",
				CR = "<CR> ",
				Esc = "<Esc> ",
				ScrollWheelDown = "<ScrollWheelDown> ",
				ScrollWheelUp = "<ScrollWheelUp> ",
				NL = "<NL> ",
				BS = "<BS> ",
				Space = "<Space> ",
				Tab = "<Tab> ",
				F1 = "<F1>",
				F2 = "<F2>",
				F3 = "<F3>",
				F4 = "<F4>",
				F5 = "<F5>",
				F6 = "<F6>",
				F7 = "<F7>",
				F8 = "<F8>",
				F9 = "<F9>",
				F10 = "<F10>",
				F11 = "<F11>",
				F12 = "<F12>",
			},
			delay = 0,
			spec = {
				{ "<leader>w", icon = "󰇚" },
				{ "<leader>b", group = "Buffer", icon = "" },
				{ "<leader>f", group = "Finder" },
				{ "<leader>l", group = "Language Tools", icon = "" },
				{ "<leader>d", group = "Debugger" },
				{ "<leader>p", group = "Playground", icon = "󱜚" },
				{ "<leader>t", group = "Terminal" },
				{ "<leader>u", group = "Utils", icon = "󰙀" },
				{ "<leader>r", group = "Http Client", icon = "󰖟" },
				{ "<leader>x", group = "Quickfix(Trouble)" },
			},
		},
	},
}
